### ISSUE TITLE
OutofMemory when run db integration

### ISSUE THREAD

**Issue by shaofeng-wang** [3-mode/lumens#2]
837656 [qtp657036354-84] WARN org.eclipse.jetty.servlet.ServletHandler -
avax.servlet.ServletException: java.lang.OutOfMemoryError: PermGen space
       at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:371)
       at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:452)
       at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:633)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
       at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
       at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
       at org.eclipse.jetty.server.Server.handle(Server.java:462)
       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
       at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
       at java.lang.Thread.run(Thread.java:744)
aused by: java.lang.OutOfMemoryError: PermGen space

**Comment by shaofeng-wang** [comment]
it is because the db connector always load dirver jar into JVM to make mem is full.
Now use a static map to cache the class loader
